"""KDS structure-code vocabulary (v34.47).

KROMI's KDS onboarding template constrains Bezeichnung 1 / Description 1
to the official structure-code list (sheet "Structure code GER" of the KDS
template, 963 entries). This table maps every structure-code word that the
freeform keyword matcher does not already resolve - keys are normalized
with text_utils.norm, values are canonical ProductCategory names - so a
mapped ProductCategory column carrying structure-code words classifies
deterministically from the customer's own taxonomy instead of falling back
to text heuristics. The category comes from each entry's own L1 family
(1. Auswahl). Collet entries ("... Spannzangen") are included although the
keyword matcher reads them as accessories: the engine code matrix defines
collet = 20008, and the structure list's L1 (Werkzeugaufnahmen) agrees.
Deburring forks ("Entgratgabel", filed under Senker in the KDS list) and
the "Weitere" free-text family are deliberately absent: they stay 'other'
and keep today's behaviour (code 19).

Generated from the official structure-code list; regenerate rather than
hand-edit when KROMI extends the taxonomy.
"""

from __future__ import annotations

KDS_STRUCTURE_CATEGORY: dict[str, str] = {
    'abrichter': 'grinding_tools',
    'abrichtkugel': 'grinding_tools',
    'abs100 abs': 'tool_holders',
    'abs100 angetriebene werkzeuge': 'tool_holders',
    'abs100 aufsteck-fräsdorn': 'tool_holders',
    'abs100 bohrfutter': 'tool_holders',
    'abs100 capto': 'tool_holders',
    'abs100 gsswf': 'tool_holders',
    'abs100 hydro-dehn': 'tool_holders',
    'abs100 kombi-aufsteck-fräsdorn': 'tool_holders',
    'abs100 mk': 'tool_holders',
    'abs100 reduzierung': 'tool_holders',
    'abs100 schrumpfen': 'tool_holders',
    'abs100 spannzangen': 'tool_holders',
    'abs100 tribos': 'tool_holders',
    'abs100 verlängerung': 'tool_holders',
    'abs100 vorsatzflansch': 'tool_holders',
    'abs100 weldon': 'tool_holders',
    'abs100 winkelfräskopf': 'tool_holders',
    'abs100 wistle notch': 'tool_holders',
    'abs25 abs': 'tool_holders',
    'abs25 angetriebene werkzeuge': 'tool_holders',
    'abs25 aufsteck-fräsdorn': 'tool_holders',
    'abs25 bohrfutter': 'tool_holders',
    'abs25 capto': 'tool_holders',
    'abs25 gsswf': 'tool_holders',
    'abs25 hydro-dehn': 'tool_holders',
    'abs25 kombi-aufsteck-fräsdorn': 'tool_holders',
    'abs25 mk': 'tool_holders',
    'abs25 reduzierung': 'tool_holders',
    'abs25 schrumpfen': 'tool_holders',
    'abs25 spannzangen': 'tool_holders',
    'abs25 tribos': 'tool_holders',
    'abs25 verlängerung': 'tool_holders',
    'abs25 weldon': 'tool_holders',
    'abs25 winkelfräskopf': 'tool_holders',
    'abs25 wistle notch': 'tool_holders',
    'abs32 abs': 'tool_holders',
    'abs32 angetriebene werkzeuge': 'tool_holders',
    'abs32 aufsteck-fräsdorn': 'tool_holders',
    'abs32 bohrfutter': 'tool_holders',
    'abs32 capto': 'tool_holders',
    'abs32 gsswf': 'tool_holders',
    'abs32 hydro-dehn': 'tool_holders',
    'abs32 kombi-aufsteck-fräsdorn': 'tool_holders',
    'abs32 mk': 'tool_holders',
    'abs32 reduzierung': 'tool_holders',
    'abs32 schrumpfen': 'tool_holders',
    'abs32 spannzangen': 'tool_holders',
    'abs32 tribos': 'tool_holders',
    'abs32 verlängerung': 'tool_holders',
    'abs32 weldon': 'tool_holders',
    'abs32 winkelfräskopf': 'tool_holders',
    'abs32 wistle notch': 'tool_holders',
    'abs40 abs': 'tool_holders',
    'abs40 angetriebene werkzeuge': 'tool_holders',
    'abs40 aufsteck-fräsdorn': 'tool_holders',
    'abs40 bohrfutter': 'tool_holders',
    'abs40 capto': 'tool_holders',
    'abs40 gsswf': 'tool_holders',
    'abs40 hydro-dehn': 'tool_holders',
    'abs40 kombi-aufsteck-fräsdorn': 'tool_holders',
    'abs40 mk': 'tool_holders',
    'abs40 reduzierung': 'tool_holders',
    'abs40 schrumpfen': 'tool_holders',
    'abs40 spannzangen': 'tool_holders',
    'abs40 tribos': 'tool_holders',
    'abs40 verlängerung': 'tool_holders',
    'abs40 weldon': 'tool_holders',
    'abs40 winkelfräskopf': 'tool_holders',
    'abs40 wistle notch': 'tool_holders',
    'abs50 abs': 'tool_holders',
    'abs50 angetriebene werkzeuge': 'tool_holders',
    'abs50 aufsteck-fräsdorn': 'tool_holders',
    'abs50 bohrfutter': 'tool_holders',
    'abs50 capto': 'tool_holders',
    'abs50 gsswf': 'tool_holders',
    'abs50 hydro-dehn': 'tool_holders',
    'abs50 kombi-aufsteck-fräsdorn': 'tool_holders',
    'abs50 mk': 'tool_holders',
    'abs50 reduzierung': 'tool_holders',
    'abs50 schrumpfen': 'tool_holders',
    'abs50 spannzangen': 'tool_holders',
    'abs50 tribos': 'tool_holders',
    'abs50 verlängerung': 'tool_holders',
    'abs50 vorsatzflansch': 'tool_holders',
    'abs50 weldon': 'tool_holders',
    'abs50 winkelfräskopf': 'tool_holders',
    'abs50 wistle notch': 'tool_holders',
    'abs63 abs': 'tool_holders',
    'abs63 angetriebene werkzeuge': 'tool_holders',
    'abs63 aufsteck-fräsdorn': 'tool_holders',
    'abs63 bohrfutter': 'tool_holders',
    'abs63 capto': 'tool_holders',
    'abs63 gsswf': 'tool_holders',
    'abs63 hydro-dehn': 'tool_holders',
    'abs63 kombi-aufsteck-fräsdorn': 'tool_holders',
    'abs63 mk': 'tool_holders',
    'abs63 reduzierung': 'tool_holders',
    'abs63 schrumpfen': 'tool_holders',
    'abs63 spannzangen': 'tool_holders',
    'abs63 tribos': 'tool_holders',
    'abs63 verlängerung': 'tool_holders',
    'abs63 vorsatzflansch': 'tool_holders',
    'abs63 weldon': 'tool_holders',
    'abs63 winkelfräskopf': 'tool_holders',
    'abs63 wistle notch': 'tool_holders',
    'abs80 abs': 'tool_holders',
    'abs80 angetriebene werkzeuge': 'tool_holders',
    'abs80 aufsteck-fräsdorn': 'tool_holders',
    'abs80 bohrfutter': 'tool_holders',
    'abs80 capto': 'tool_holders',
    'abs80 gsswf': 'tool_holders',
    'abs80 hydro-dehn': 'tool_holders',
    'abs80 kombi-aufsteck-fräsdorn': 'tool_holders',
    'abs80 mk': 'tool_holders',
    'abs80 reduzierung': 'tool_holders',
    'abs80 schrumpfen': 'tool_holders',
    'abs80 spannzangen': 'tool_holders',
    'abs80 tribos': 'tool_holders',
    'abs80 verlängerung': 'tool_holders',
    'abs80 vorsatzflansch': 'tool_holders',
    'abs80 weldon': 'tool_holders',
    'abs80 winkelfräskopf': 'tool_holders',
    'abs80 wistle notch': 'tool_holders',
    'außen stoßwerkzeug hss': 'gear_cutting',
    'außen stoßwerkzeug pm': 'gear_cutting',
    'außen stoßwerkzeug vhm': 'gear_cutting',
    'bmt45 abs': 'tool_holders',
    'bmt45 angetriebene werkzeuge': 'tool_holders',
    'bmt45 aufsteck-fräsdorn': 'tool_holders',
    'bmt45 bohrfutter': 'tool_holders',
    'bmt45 capto': 'tool_holders',
    'bmt45 gsswf': 'tool_holders',
    'bmt45 hydro-dehn': 'tool_holders',
    'bmt45 kombi-aufsteck-fräsdorn': 'tool_holders',
    'bmt45 mk': 'tool_holders',
    'bmt45 reduzierung': 'tool_holders',
    'bmt45 schrumpfen': 'tool_holders',
    'bmt45 spannzangen': 'tool_holders',
    'bmt45 tribos': 'tool_holders',
    'bmt45 verlängerung': 'tool_holders',
    'bmt45 weldon': 'tool_holders',
    'bmt45 winkelfräskopf': 'tool_holders',
    'bmt45 wistle notch': 'tool_holders',
    'bürste': 'brushes',
    'capto abs': 'tool_holders',
    'capto angetriebene werkzeuge': 'tool_holders',
    'capto aufsteck-fräsdorn': 'tool_holders',
    'capto bohrfutter': 'tool_holders',
    'capto capto': 'tool_holders',
    'capto gsswf': 'tool_holders',
    'capto hydro-dehn': 'tool_holders',
    'capto kombi-aufsteck-fräsdorn': 'tool_holders',
    'capto mk': 'tool_holders',
    'capto reduzierung': 'tool_holders',
    'capto schrumpfen': 'tool_holders',
    'capto spannzangen': 'tool_holders',
    'capto tribos': 'tool_holders',
    'capto varilock': 'tool_holders',
    'capto verlängerung': 'tool_holders',
    'capto weldon': 'tool_holders',
    'capto winkelfräskopf': 'tool_holders',
    'capto wistle notch': 'tool_holders',
    'feste zentrierspitze hm': 'center_points',
    'feste zentrierspitze stahl': 'center_points',
    'flachsenker cbn': 'counterbores',
    'flachsenker diamant': 'counterbores',
    'flachsenker hm': 'counterbores',
    'flachsenker hss': 'counterbores',
    'flachsenker hss-e/hsco': 'counterbores',
    'flachsenker pkd': 'counterbores',
    'flachsenker vhm': 'counterbores',
    'flex- hone': 'grinding_tools',
    'formstahl hss': 'form_steel',
    'formstahl vhm': 'form_steel',
    'halter spannzangenfutter': 'holders',
    'honahlen': 'honing_tools',
    'honhülse': 'grinding_tools',
    'honstein': 'grinding_tools',
    'hsk100 abs': 'tool_holders',
    'hsk100 angetriebene werkzeuge': 'tool_holders',
    'hsk100 aufsteck-fräsdorn': 'tool_holders',
    'hsk100 bohrfutter': 'tool_holders',
    'hsk100 capto': 'tool_holders',
    'hsk100 gsswf': 'tool_holders',
    'hsk100 hydro-dehn': 'tool_holders',
    'hsk100 kombi-aufsteck-fräsdorn': 'tool_holders',
    'hsk100 mhd': 'tool_holders',
    'hsk100 mk': 'tool_holders',
    'hsk100 reduzierung': 'tool_holders',
    'hsk100 schrumpfen': 'tool_holders',
    'hsk100 spannzangen': 'tool_holders',
    'hsk100 tribos': 'tool_holders',
    'hsk100 varilock': 'tool_holders',
    'hsk100 verlängerung': 'tool_holders',
    'hsk100 weldon': 'tool_holders',
    'hsk100 winkelfräskopf': 'tool_holders',
    'hsk100 wistle notch': 'tool_holders',
    'hsk32': 'tool_holders',
    'hsk32 abs': 'tool_holders',
    'hsk32 angetriebene werkzeuge': 'tool_holders',
    'hsk32 aufsteck-fräsdorn': 'tool_holders',
    'hsk32 bohrfutter': 'tool_holders',
    'hsk32 capto': 'tool_holders',
    'hsk32 gsswf': 'tool_holders',
    'hsk32 hydro-dehn': 'tool_holders',
    'hsk32 kombi-aufsteck-fräsdorn': 'tool_holders',
    'hsk32 mhd': 'tool_holders',
    'hsk32 mk': 'tool_holders',
    'hsk32 reduzierung': 'tool_holders',
    'hsk32 schrumpfen': 'tool_holders',
    'hsk32 spannzangen': 'tool_holders',
    'hsk32 tribos': 'tool_holders',
    'hsk32 verlängerung': 'tool_holders',
    'hsk32 weldon': 'tool_holders',
    'hsk32 winkelfräskopf': 'tool_holders',
    'hsk32 wistle notch': 'tool_holders',
    'hsk50 abs': 'tool_holders',
    'hsk50 angetriebene werkzeuge': 'tool_holders',
    'hsk50 aufsteck-fräsdorn': 'tool_holders',
    'hsk50 bohrfutter': 'tool_holders',
    'hsk50 capto': 'tool_holders',
    'hsk50 gsswf': 'tool_holders',
    'hsk50 hydro-dehn': 'tool_holders',
    'hsk50 kombi-aufsteck-fräsdorn': 'tool_holders',
    'hsk50 mhd': 'tool_holders',
    'hsk50 mk': 'tool_holders',
    'hsk50 reduzierung': 'tool_holders',
    'hsk50 schrumpfen': 'tool_holders',
    'hsk50 spannzangen': 'tool_holders',
    'hsk50 tribos': 'tool_holders',
    'hsk50 varilock': 'tool_holders',
    'hsk50 verlängerung': 'tool_holders',
    'hsk50 weldon': 'tool_holders',
    'hsk50 winkelfräskopf': 'tool_holders',
    'hsk50 wistle notch': 'tool_holders',
    'hsk63 abs': 'tool_holders',
    'hsk63 angetriebene werkzeuge': 'tool_holders',
    'hsk63 aufsteck-fräsdorn': 'tool_holders',
    'hsk63 bohrfutter': 'tool_holders',
    'hsk63 capto': 'tool_holders',
    'hsk63 gsswf': 'tool_holders',
    'hsk63 hydro-dehn': 'tool_holders',
    'hsk63 kombi-aufsteck-fräsdorn': 'tool_holders',
    'hsk63 mhd': 'tool_holders',
    'hsk63 mk': 'tool_holders',
    'hsk63 reduzierung': 'tool_holders',
    'hsk63 schrumpfen': 'tool_holders',
    'hsk63 spannzangen': 'tool_holders',
    'hsk63 tribos': 'tool_holders',
    'hsk63 varilock': 'tool_holders',
    'hsk63 verlängerung': 'tool_holders',
    'hsk63 weldon': 'tool_holders',
    'hsk63 winkelfräskopf': 'tool_holders',
    'hsk63 wistle notch': 'tool_holders',
    'innen stoßwerkzeug hss': 'gear_cutting',
    'innen stoßwerkzeug pm': 'gear_cutting',
    'innen stoßwerkzeug vhm': 'gear_cutting',
    'kegelsenker cbn': 'counterbores',
    'kegelsenker diamant': 'counterbores',
    'kegelsenker hm': 'counterbores',
    'kegelsenker hss': 'counterbores',
    'kegelsenker hss-e/hsco': 'counterbores',
    'kegelsenker pkd': 'counterbores',
    'kegelsenker vhm': 'counterbores',
    'km abs': 'tool_holders',
    'km angetriebene werkzeuge': 'tool_holders',
    'km aufsteck-fräsdorn': 'tool_holders',
    'km bohrfutter': 'tool_holders',
    'km capto': 'tool_holders',
    'km gsswf': 'tool_holders',
    'km hydro-dehn': 'tool_holders',
    'km kombi-aufsteck-fräsdorn': 'tool_holders',
    'km mk': 'tool_holders',
    'km reduzierung': 'tool_holders',
    'km schrumpfen': 'tool_holders',
    'km spannzangen': 'tool_holders',
    'km tribos': 'tool_holders',
    'km verlängerung': 'tool_holders',
    'km weldon': 'tool_holders',
    'km winkelfräskopf': 'tool_holders',
    'km wistle notch': 'tool_holders',
    'masbt32 abs': 'tool_holders',
    'masbt32 angetriebene werkzeuge': 'tool_holders',
    'masbt32 aufsteck-fräsdorn': 'tool_holders',
    'masbt32 bohrfutter': 'tool_holders',
    'masbt32 capto': 'tool_holders',
    'masbt32 gsswf': 'tool_holders',
    'masbt32 hydro-dehn': 'tool_holders',
    'masbt32 kombi-aufsteck-fräsdorn': 'tool_holders',
    'masbt32 mk': 'tool_holders',
    'masbt32 reduzierung': 'tool_holders',
    'masbt32 schrumpfen': 'tool_holders',
    'masbt32 spannzangen': 'tool_holders',
    'masbt32 tribos': 'tool_holders',
    'masbt32 verlängerung': 'tool_holders',
    'masbt32 weldon': 'tool_holders',
    'masbt32 winkelfräskopf': 'tool_holders',
    'masbt32 wistle notch': 'tool_holders',
    'masbt40 abs': 'tool_holders',
    'masbt40 angetriebene werkzeuge': 'tool_holders',
    'masbt40 aufsteck-fräsdorn': 'tool_holders',
    'masbt40 bohrfutter': 'tool_holders',
    'masbt40 capto': 'tool_holders',
    'masbt40 gsswf': 'tool_holders',
    'masbt40 hydro-dehn': 'tool_holders',
    'masbt40 kombi-aufsteck-fräsdorn': 'tool_holders',
    'masbt40 mk': 'tool_holders',
    'masbt40 reduzierung': 'tool_holders',
    'masbt40 schrumpfen': 'tool_holders',
    'masbt40 spannzangen': 'tool_holders',
    'masbt40 tribos': 'tool_holders',
    'masbt40 verlängerung': 'tool_holders',
    'masbt40 weldon': 'tool_holders',
    'masbt40 winkelfräskopf': 'tool_holders',
    'masbt40 wistle notch': 'tool_holders',
    'masbt50 abs': 'tool_holders',
    'masbt50 angetriebene werkzeuge': 'tool_holders',
    'masbt50 aufsteck-fräsdorn': 'tool_holders',
    'masbt50 bohrfutter': 'tool_holders',
    'masbt50 capto': 'tool_holders',
    'masbt50 gsswf': 'tool_holders',
    'masbt50 hydro-dehn': 'tool_holders',
    'masbt50 kombi-aufsteck-fräsdorn': 'tool_holders',
    'masbt50 mk': 'tool_holders',
    'masbt50 reduzierung': 'tool_holders',
    'masbt50 schrumpfen': 'tool_holders',
    'masbt50 spannzangen': 'tool_holders',
    'masbt50 tribos': 'tool_holders',
    'masbt50 verlängerung': 'tool_holders',
    'masbt50 weldon': 'tool_holders',
    'masbt50 winkelfräskopf': 'tool_holders',
    'masbt50 wistle notch': 'tool_holders',
    'mitlaufende zentrierspitze hm': 'center_points',
    'mitlaufende zentrierspitze stahl': 'center_points',
    'mk abs': 'tool_holders',
    'mk angetriebene werkzeuge': 'tool_holders',
    'mk aufsteck-fräsdorn': 'tool_holders',
    'mk bohrfutter': 'tool_holders',
    'mk capto': 'tool_holders',
    'mk gsswf': 'tool_holders',
    'mk hydro-dehn': 'tool_holders',
    'mk kombi-aufsteck-fräsdorn': 'tool_holders',
    'mk mk': 'tool_holders',
    'mk reduzierung': 'tool_holders',
    'mk schrumpfen': 'tool_holders',
    'mk spannzangen': 'tool_holders',
    'mk stellhülse': 'tool_holders',
    'mk tribos': 'tool_holders',
    'mk verlängerung': 'tool_holders',
    'mk weldon': 'tool_holders',
    'mk winkelfräskopf': 'tool_holders',
    'mk wistle notch': 'tool_holders',
    'räumwerkzeug': 'broaches',
    'rückwärtssenker cbn': 'counterbores',
    'rückwärtssenker diamant': 'counterbores',
    'rückwärtssenker hm': 'counterbores',
    'rückwärtssenker hss': 'counterbores',
    'rückwärtssenker hss-e/hsco': 'counterbores',
    'rückwärtssenker pkd': 'counterbores',
    'rückwärtssenker vhm': 'counterbores',
    'schleifband': 'grinding_tools',
    'schleiffächer': 'grinding_tools',
    'schleifkappen': 'grinding_tools',
    'schleifscheibe': 'grinding_tools',
    'schleifstift': 'grinding_tools',
    'schweißen': 'welding',
    'sk30 abs': 'tool_holders',
    'sk30 angetriebene werkzeuge': 'tool_holders',
    'sk30 aufsteck-fräsdorn': 'tool_holders',
    'sk30 bohrfutter': 'tool_holders',
    'sk30 capto': 'tool_holders',
    'sk30 gsswf': 'tool_holders',
    'sk30 hydro-dehn': 'tool_holders',
    'sk30 kombi-aufsteck-fräsdorn': 'tool_holders',
    'sk30 mk': 'tool_holders',
    'sk30 reduzierung': 'tool_holders',
    'sk30 schrumpfen': 'tool_holders',
    'sk30 spannzangen': 'tool_holders',
    'sk30 tribos': 'tool_holders',
    'sk30 verlängerung': 'tool_holders',
    'sk30 weldon': 'tool_holders',
    'sk30 winkelfräskopf': 'tool_holders',
    'sk30 wistle notch': 'tool_holders',
    'sk40 abs': 'tool_holders',
    'sk40 angetriebene werkzeuge': 'tool_holders',
    'sk40 aufsteck-fräsdorn': 'tool_holders',
    'sk40 bohrfutter': 'tool_holders',
    'sk40 capto': 'tool_holders',
    'sk40 gsswf': 'tool_holders',
    'sk40 hydro-dehn': 'tool_holders',
    'sk40 kombi-aufsteck-fräsdorn': 'tool_holders',
    'sk40 mk': 'tool_holders',
    'sk40 reduzierung': 'tool_holders',
    'sk40 schrumpfen': 'tool_holders',
    'sk40 spannzangen': 'tool_holders',
    'sk40 tribos': 'tool_holders',
    'sk40 verlängerung': 'tool_holders',
    'sk40 weldon': 'tool_holders',
    'sk40 winkelfräskopf': 'tool_holders',
    'sk40 wistle notch': 'tool_holders',
    'sk45 abs': 'tool_holders',
    'sk45 angetriebene werkzeuge': 'tool_holders',
    'sk45 aufsteck-fräsdorn': 'tool_holders',
    'sk45 bohrfutter': 'tool_holders',
    'sk45 capto': 'tool_holders',
    'sk45 gsswf': 'tool_holders',
    'sk45 hydro-dehn': 'tool_holders',
    'sk45 kombi-aufsteck-fräsdorn': 'tool_holders',
    'sk45 mk': 'tool_holders',
    'sk45 reduzierung': 'tool_holders',
    'sk45 schrumpfen': 'tool_holders',
    'sk45 spannzangen': 'tool_holders',
    'sk45 tribos': 'tool_holders',
    'sk45 verlängerung': 'tool_holders',
    'sk45 weldon': 'tool_holders',
    'sk45 winkelfräskopf': 'tool_holders',
    'sk45 wistle notch': 'tool_holders',
    'sk50 abs': 'tool_holders',
    'sk50 angetriebene werkzeuge': 'tool_holders',
    'sk50 aufsteck-fräsdorn': 'tool_holders',
    'sk50 bohrfutter': 'tool_holders',
    'sk50 capto': 'tool_holders',
    'sk50 gsswf': 'tool_holders',
    'sk50 hydro-dehn': 'tool_holders',
    'sk50 kombi-aufsteck-fräsdorn': 'tool_holders',
    'sk50 mk': 'tool_holders',
    'sk50 reduzierung': 'tool_holders',
    'sk50 schrumpfen': 'tool_holders',
    'sk50 spannzangen': 'tool_holders',
    'sk50 tribos': 'tool_holders',
    'sk50 varilock': 'tool_holders',
    'sk50 verlängerung': 'tool_holders',
    'sk50 weldon': 'tool_holders',
    'sk50 winkelfräskopf': 'tool_holders',
    'sk50 wistle notch': 'tool_holders',
    'spannzange': 'accessories',
    'stirnseiten mitnehmer': 'center_points',
    'stufensenker cbn': 'counterbores',
    'stufensenker diamant': 'counterbores',
    'stufensenker hm': 'counterbores',
    'stufensenker hss': 'counterbores',
    'stufensenker hss-e/hsco': 'counterbores',
    'stufensenker pkd': 'counterbores',
    'stufensenker vhm': 'counterbores',
    'trennscheibe': 'grinding_tools',
    'varia varia weldon': 'tool_holders',
    'varilock abs': 'tool_holders',
    'varilock angetriebene werkzeuge': 'tool_holders',
    'varilock aufsteck-fräsdorn': 'tool_holders',
    'varilock bohrfutter': 'tool_holders',
    'varilock capto': 'tool_holders',
    'varilock gsswf': 'tool_holders',
    'varilock hydro-dehn': 'tool_holders',
    'varilock kombi-aufsteck-fräsdorn': 'tool_holders',
    'varilock mk': 'tool_holders',
    'varilock reduzierung': 'tool_holders',
    'varilock schrumpfen': 'tool_holders',
    'varilock spannzangen': 'tool_holders',
    'varilock tribos': 'tool_holders',
    'varilock verlängerung': 'tool_holders',
    'varilock weldon': 'tool_holders',
    'varilock winkelfräskopf': 'tool_holders',
    'varilock wistle notch': 'tool_holders',
    'vdi abs': 'tool_holders',
    'vdi angetriebene werkzeuge': 'tool_holders',
    'vdi b1': 'tool_holders',
    'vdi b2': 'tool_holders',
    'vdi b3': 'tool_holders',
    'vdi b4': 'tool_holders',
    'vdi b5': 'tool_holders',
    'vdi b6': 'tool_holders',
    'vdi b7': 'tool_holders',
    'vdi b8': 'tool_holders',
    'vdi c1': 'tool_holders',
    'vdi c2': 'tool_holders',
    'vdi c4': 'tool_holders',
    'vdi capto3': 'tool_holders',
    'vdi capto4': 'tool_holders',
    'vdi capto5': 'tool_holders',
    'vdi capto6': 'tool_holders',
    'vdi capto8': 'tool_holders',
    'vdi d1': 'tool_holders',
    'vdi d2': 'tool_holders',
    'vdi e1': 'tool_holders',
    'vdi e2': 'tool_holders',
    'vdi e4': 'tool_holders',
    'vdi reduzierung': 'tool_holders',
    'vdi spannzangen': 'tool_holders',
    'vdi tribos': 'tool_holders',
    'vdi varilock': 'tool_holders',
    'vdi verlängerung': 'tool_holders',
    'vdi winkelfräskopf': 'tool_holders',
    'vdi16  abs': 'tool_holders',
    'vdi16  angetriebene werkzeuge': 'tool_holders',
    'vdi16  b1': 'tool_holders',
    'vdi16  b2': 'tool_holders',
    'vdi16  b3': 'tool_holders',
    'vdi16  b4': 'tool_holders',
    'vdi16  b5': 'tool_holders',
    'vdi16  b6': 'tool_holders',
    'vdi16  b7': 'tool_holders',
    'vdi16  b8': 'tool_holders',
    'vdi16  c1': 'tool_holders',
    'vdi16  c2': 'tool_holders',
    'vdi16  c4': 'tool_holders',
    'vdi16  capto3': 'tool_holders',
    'vdi16  capto4': 'tool_holders',
    'vdi16  capto5': 'tool_holders',
    'vdi16  capto6': 'tool_holders',
    'vdi16  capto8': 'tool_holders',
    'vdi16  d1': 'tool_holders',
    'vdi16  d2': 'tool_holders',
    'vdi16  e1': 'tool_holders',
    'vdi16  e2': 'tool_holders',
    'vdi16  e4': 'tool_holders',
    'vdi16  reduzierung': 'tool_holders',
    'vdi16  spannzangen': 'tool_holders',
    'vdi16  tribos': 'tool_holders',
    'vdi16  varilock': 'tool_holders',
    'vdi16  verlängerung': 'tool_holders',
    'vdi16  winkelfräßkopf': 'tool_holders',
    'vdi20  abs': 'tool_holders',
    'vdi20  angetriebene werkzeuge': 'tool_holders',
    'vdi20  b1': 'tool_holders',
    'vdi20  b2': 'tool_holders',
    'vdi20  b3': 'tool_holders',
    'vdi20  b4': 'tool_holders',
    'vdi20  b5': 'tool_holders',
    'vdi20  b6': 'tool_holders',
    'vdi20  b7': 'tool_holders',
    'vdi20  b8': 'tool_holders',
    'vdi20  c1': 'tool_holders',
    'vdi20  c2': 'tool_holders',
    'vdi20  c4': 'tool_holders',
    'vdi20  capto3': 'tool_holders',
    'vdi20  capto4': 'tool_holders',
    'vdi20  capto5': 'tool_holders',
    'vdi20  capto6': 'tool_holders',
    'vdi20  capto8': 'tool_holders',
    'vdi20  d1': 'tool_holders',
    'vdi20  d2': 'tool_holders',
    'vdi20  e1': 'tool_holders',
    'vdi20  e2': 'tool_holders',
    'vdi20  e4': 'tool_holders',
    'vdi20  reduzierung': 'tool_holders',
    'vdi20  spannzangen': 'tool_holders',
    'vdi20  tribos': 'tool_holders',
    'vdi20  varilock': 'tool_holders',
    'vdi20  verlängerung': 'tool_holders',
    'vdi20  winkelfräßkopf': 'tool_holders',
    'vdi25  abs': 'tool_holders',
    'vdi25  angetriebene werkzeuge': 'tool_holders',
    'vdi25  b1': 'tool_holders',
    'vdi25  b2': 'tool_holders',
    'vdi25  b3': 'tool_holders',
    'vdi25  b4': 'tool_holders',
    'vdi25  b5': 'tool_holders',
    'vdi25  b6': 'tool_holders',
    'vdi25  b7': 'tool_holders',
    'vdi25  b8': 'tool_holders',
    'vdi25  c1': 'tool_holders',
    'vdi25  c2': 'tool_holders',
    'vdi25  c4': 'tool_holders',
    'vdi25  capto3': 'tool_holders',
    'vdi25  capto4': 'tool_holders',
    'vdi25  capto5': 'tool_holders',
    'vdi25  capto6': 'tool_holders',
    'vdi25  capto8': 'tool_holders',
    'vdi25  d1': 'tool_holders',
    'vdi25  d2': 'tool_holders',
    'vdi25  e1': 'tool_holders',
    'vdi25  e2': 'tool_holders',
    'vdi25  e4': 'tool_holders',
    'vdi25  reduzierung': 'tool_holders',
    'vdi25  spannzangen': 'tool_holders',
    'vdi25  tribos': 'tool_holders',
    'vdi25  varilock': 'tool_holders',
    'vdi25  verlängerung': 'tool_holders',
    'vdi25  winkelfräßkopf': 'tool_holders',
    'vdi30  abs': 'tool_holders',
    'vdi30  angetriebene werkzeuge': 'tool_holders',
    'vdi30  b1': 'tool_holders',
    'vdi30  b2': 'tool_holders',
    'vdi30  b3': 'tool_holders',
    'vdi30  b4': 'tool_holders',
    'vdi30  b5': 'tool_holders',
    'vdi30  b6': 'tool_holders',
    'vdi30  b7': 'tool_holders',
    'vdi30  b8': 'tool_holders',
    'vdi30  c1': 'tool_holders',
    'vdi30  c2': 'tool_holders',
    'vdi30  c4': 'tool_holders',
    'vdi30  capto3': 'tool_holders',
    'vdi30  capto4': 'tool_holders',
    'vdi30  capto5': 'tool_holders',
    'vdi30  capto6': 'tool_holders',
    'vdi30  capto8': 'tool_holders',
    'vdi30  d1': 'tool_holders',
    'vdi30  d2': 'tool_holders',
    'vdi30  e1': 'tool_holders',
    'vdi30  e2': 'tool_holders',
    'vdi30  e4': 'tool_holders',
    'vdi30  reduzierung': 'tool_holders',
    'vdi30  spannzangen': 'tool_holders',
    'vdi30  tribos': 'tool_holders',
    'vdi30  varilock': 'tool_holders',
    'vdi30  verlängerung': 'tool_holders',
    'vdi30  winkelfräßkopf': 'tool_holders',
    'vdi40  abs': 'tool_holders',
    'vdi40  angetriebene werkzeuge': 'tool_holders',
    'vdi40  b1': 'tool_holders',
    'vdi40  b2': 'tool_holders',
    'vdi40  b3': 'tool_holders',
    'vdi40  b4': 'tool_holders',
    'vdi40  b5': 'tool_holders',
    'vdi40  b6': 'tool_holders',
    'vdi40  b7': 'tool_holders',
    'vdi40  b8': 'tool_holders',
    'vdi40  c1': 'tool_holders',
    'vdi40  c2': 'tool_holders',
    'vdi40  c4': 'tool_holders',
    'vdi40  capto3': 'tool_holders',
    'vdi40  capto4': 'tool_holders',
    'vdi40  capto5': 'tool_holders',
    'vdi40  capto6': 'tool_holders',
    'vdi40  capto8': 'tool_holders',
    'vdi40  d1': 'tool_holders',
    'vdi40  d2': 'tool_holders',
    'vdi40  e1': 'tool_holders',
    'vdi40  e2': 'tool_holders',
    'vdi40  e4': 'tool_holders',
    'vdi40  reduzierung': 'tool_holders',
    'vdi40  spannzangen': 'tool_holders',
    'vdi40  tribos': 'tool_holders',
    'vdi40  varilock': 'tool_holders',
    'vdi40  verlängerung': 'tool_holders',
    'vdi40  winkelfräßkopf': 'tool_holders',
    'vdi50  abs': 'tool_holders',
    'vdi50  angetriebene werkzeuge': 'tool_holders',
    'vdi50  b1': 'tool_holders',
    'vdi50  b2': 'tool_holders',
    'vdi50  b3': 'tool_holders',
    'vdi50  b4': 'tool_holders',
    'vdi50  b5': 'tool_holders',
    'vdi50  b6': 'tool_holders',
    'vdi50  b7': 'tool_holders',
    'vdi50  b8': 'tool_holders',
    'vdi50  c1': 'tool_holders',
    'vdi50  c2': 'tool_holders',
    'vdi50  c4': 'tool_holders',
    'vdi50  capto3': 'tool_holders',
    'vdi50  capto4': 'tool_holders',
    'vdi50  capto5': 'tool_holders',
    'vdi50  capto6': 'tool_holders',
    'vdi50  capto8': 'tool_holders',
    'vdi50  d1': 'tool_holders',
    'vdi50  d2': 'tool_holders',
    'vdi50  e1': 'tool_holders',
    'vdi50  e2': 'tool_holders',
    'vdi50  e4': 'tool_holders',
    'vdi50  reduzierung': 'tool_holders',
    'vdi50  spannzangen': 'tool_holders',
    'vdi50  tribos': 'tool_holders',
    'vdi50  varilock': 'tool_holders',
    'vdi50  verlängerung': 'tool_holders',
    'vdi50  winkelfräßkopf': 'tool_holders',
    'wechselplatte bohren vhm': 'inserts',
}
