/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Defaults */
        get: operations["defaults_api_v1_settings_defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Workbook */
        post: operations["upload_workbook_api_v1_workbooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workbooks/{workbook_id}/sheets/{sheet}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect Sheet */
        get: operations["inspect_sheet_api_v1_workbooks__workbook_id__sheets__sheet__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workbooks/{workbook_id}/mapping/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Mapping */
        post: operations["check_mapping_api_v1_workbooks__workbook_id__mapping_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Tools */
        get: operations["run_tools_api_v1_runs__run_id__tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/workbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Workbook */
        get: operations["run_workbook_api_v1_runs__run_id__workbook_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_workbook_api_v1_workbooks_post */
        Body_upload_workbook_api_v1_workbooks_post: {
            /** File */
            file: string;
        };
        /** BucketOut */
        BucketOut: {
            /** Position */
            position: number;
            /** Label */
            label: string;
            /** Ktc Count */
            ktc_count: number;
            /** Kanban Count */
            kanban_count: number;
            /** Helix Cabinets */
            helix_cabinets: number;
            /** Carousel Cabinets */
            carousel_cabinets: number;
            /** Locker A Cabinets */
            locker_a_cabinets: number;
            /** Locker B Cabinets */
            locker_b_cabinets: number;
            /** Locker C Cabinets */
            locker_c_cabinets: number;
            /** Total Cabinets */
            total_cabinets: number;
        };
        /**
         * ColumnMappingIn
         * @description Source column per planning field; ``None`` = not mapped.
         */
        ColumnMappingIn: {
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Consumption */
            consumption: string;
            /** Description 2 */
            description_2?: string | null;
            /** Category */
            category?: string | null;
            /** Supplier Code */
            supplier_code?: string | null;
            /** Size */
            size?: string | null;
            /** Pack Units */
            pack_units?: string | null;
            /** Year */
            year?: string | null;
            /** Program */
            program?: string | null;
            /** Restocking */
            restocking?: string | null;
            /** Site */
            site?: string | null;
            /** Std Special */
            std_special?: string | null;
            /** Dimensions */
            dimensions?: string | null;
            /** Regrind */
            regrind?: string | null;
            /** System Type */
            system_type?: string | null;
            /** Stock */
            stock?: string | null;
        };
        /** DefaultsOut */
        DefaultsOut: {
            /** Header Row */
            header_row: number;
            planning: components["schemas"]["PlanningIn"];
            scope: components["schemas"]["ScopeIn"];
            export: components["schemas"]["ExportIn"];
            /** Limits */
            limits: {
                [key: string]: [
                    number | null,
                    number | null
                ];
            };
            /** Labels */
            labels: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** Choices */
            choices: {
                [key: string]: string[];
            };
        };
        /** ExportIn */
        ExportIn: {
            /**
             * Include Planogram
             * @default true
             */
            include_planogram: boolean;
            /**
             * Include Technical
             * @default false
             */
            include_technical: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MappingCheckIn */
        MappingCheckIn: {
            /** Sheet */
            sheet: string;
            /**
             * Header Row
             * @default 1
             */
            header_row: number;
            mapping: components["schemas"]["ColumnMappingIn"];
        };
        /** MappingCheckOut */
        MappingCheckOut: {
            /** Ok */
            ok: boolean;
            /** Conflicts */
            conflicts: {
                [key: string]: string[];
            };
            /** Missing Columns */
            missing_columns: string[];
        };
        /**
         * PlanningIn
         * @description The planning controls; field names and defaults are ``RunSettings``'.
         */
        PlanningIn: {
            /**
             * Use Description 2
             * @default true
             */
            use_description_2: boolean;
            /**
             * Year Mode
             * @default all_rows
             */
            year_mode: string;
            /**
             * Dedup Mode
             * @default code_supplier
             */
            dedup_mode: string;
            /**
             * Ktc Threshold
             * @default 1
             */
            ktc_threshold: number;
            /**
             * Optional Thresholds Active
             * @default false
             */
            optional_thresholds_active: boolean;
            /**
             * Per Class Thresholds
             * @default []
             */
            per_class_thresholds: [
                string,
                number
            ][];
            /**
             * Insert Pack Units
             * @default 10
             */
            insert_pack_units: number;
            /**
             * Helix Threshold
             * @default 6
             */
            helix_threshold: number;
            /**
             * Consumption Months
             * @default 12
             */
            consumption_months: number;
            /**
             * Helix Overfill Factor
             * @default 1.1
             */
            helix_overfill_factor: number;
            /**
             * Min Carousel Allocation
             * @default 3
             */
            min_carousel_allocation: number;
            /**
             * Coverage Days
             * @default 20
             */
            coverage_days: number;
            /**
             * Coverage Days Special
             * @default 20
             */
            coverage_days_special: number;
            /**
             * Special Ktc
             * @default false
             */
            special_ktc: boolean;
            /**
             * Carousel Reserve Factor
             * @default 0.85
             */
            carousel_reserve_factor: number;
            /**
             * Carousel Fill Ceiling
             * @default 1
             */
            carousel_fill_ceiling: number;
            /**
             * Enable Rebalancer
             * @default true
             */
            enable_rebalancer: boolean;
            /**
             * Underuse Threshold Pct
             * @default 30
             */
            underuse_threshold_pct: number;
            /**
             * Capacity Buffer Pct
             * @default 15
             */
            capacity_buffer_pct: number;
            /**
             * Restock Categories
             * @default []
             */
            restock_categories: string[];
            /**
             * Pack Hint Extraction
             * @default true
             */
            pack_hint_extraction: boolean;
            /**
             * Bulk Routing
             * @default false
             */
            bulk_routing: boolean;
            /**
             * Force Screws Kanban
             * @default false
             */
            force_screws_kanban: boolean;
            /**
             * N Supply Points
             * @default 1
             */
            n_supply_points: number;
            /**
             * Sp Mode
             * @default replicate
             */
            sp_mode: string;
            /**
             * Calc Mode
             * @default combined
             */
            calc_mode: string;
            /**
             * Op Mode
             * @default
             */
            op_mode: string;
            /**
             * Max Carousels
             * @default 2
             */
            max_carousels: number;
            /**
             * Fixed Headroom Pct
             * @default 10
             */
            fixed_headroom_pct: number;
            /**
             * Fixed Allow Spill
             * @default true
             */
            fixed_allow_spill: boolean;
            /**
             * Fixed Stock Promotion
             * @default false
             */
            fixed_stock_promotion: boolean;
            /**
             * Fixed Stock Months
             * @default 3
             */
            fixed_stock_months: number;
            /**
             * Fixed Machines
             * @default []
             */
            fixed_machines: [
                number,
                number,
                number,
                number,
                number,
                number
            ][];
        };
        /** RunCreate */
        RunCreate: {
            /** Workbook Id */
            workbook_id: number;
            settings: components["schemas"]["RunRequest"];
        };
        /** RunError */
        RunError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: unknown;
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: number;
            /** Workbook Id */
            workbook_id: number;
            /** Status */
            status: string;
            /** Engine Build */
            engine_build: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
            error: components["schemas"]["RunError"] | null;
            /** Notes */
            notes: string[];
            summary: components["schemas"]["RunSummaryOut"] | null;
            /**
             * Reused
             * @default false
             */
            reused: boolean;
        };
        /**
         * RunRequest
         * @description Everything one planning run needs besides the workbook itself.
         */
        RunRequest: {
            /** Sheet */
            sheet: string;
            /**
             * Header Row
             * @default 1
             */
            header_row: number;
            mapping: components["schemas"]["ColumnMappingIn"];
            /**
             * @default {
             *       "use_description_2": true,
             *       "year_mode": "all_rows",
             *       "dedup_mode": "code_supplier",
             *       "ktc_threshold": 1,
             *       "optional_thresholds_active": false,
             *       "per_class_thresholds": [],
             *       "insert_pack_units": 10,
             *       "helix_threshold": 6,
             *       "consumption_months": 12,
             *       "helix_overfill_factor": 1.1,
             *       "min_carousel_allocation": 3,
             *       "coverage_days": 20,
             *       "coverage_days_special": 20,
             *       "special_ktc": false,
             *       "carousel_reserve_factor": 0.85,
             *       "carousel_fill_ceiling": 1,
             *       "enable_rebalancer": true,
             *       "underuse_threshold_pct": 30,
             *       "capacity_buffer_pct": 15,
             *       "restock_categories": [],
             *       "pack_hint_extraction": true,
             *       "bulk_routing": false,
             *       "force_screws_kanban": false,
             *       "n_supply_points": 1,
             *       "sp_mode": "replicate",
             *       "calc_mode": "combined",
             *       "op_mode": "",
             *       "max_carousels": 2,
             *       "fixed_headroom_pct": 10,
             *       "fixed_allow_spill": true,
             *       "fixed_stock_promotion": false,
             *       "fixed_stock_months": 3,
             *       "fixed_machines": []
             *     }
             */
            planning: components["schemas"]["PlanningIn"];
            /**
             * @default {
             *       "customer": "",
             *       "site": "",
             *       "ktc_id": "191",
             *       "apply_overrides": true
             *     }
             */
            scope: components["schemas"]["ScopeIn"];
            /**
             * @default {
             *       "include_planogram": true,
             *       "include_technical": false
             *     }
             */
            export: components["schemas"]["ExportIn"];
            /**
             * Program To Sp
             * @default {}
             */
            program_to_sp: {
                [key: string]: number;
            };
        };
        /** RunSummaryOut */
        RunSummaryOut: {
            /** Customer */
            customer: string;
            /** Site */
            site: string;
            /** Grand */
            grand: {
                [key: string]: unknown;
            };
            /** Buckets */
            buckets: components["schemas"]["BucketOut"][];
            /** Validation Issues */
            validation_issues: string[];
            /** Export Problems */
            export_problems: string[];
            /** Export Notes */
            export_notes: string;
        };
        /**
         * ScopeIn
         * @description Whose run this is (Run_Metadata, override scope) and the numbering KTC-ID.
         */
        ScopeIn: {
            /**
             * Customer
             * @default
             */
            customer: string;
            /**
             * Site
             * @default
             */
            site: string;
            /**
             * Ktc Id
             * @default 191
             */
            ktc_id: string;
            /**
             * Apply Overrides
             * @default true
             */
            apply_overrides: boolean;
        };
        /** SheetOut */
        SheetOut: {
            /** Sheet */
            sheet: string;
            /** Header Row */
            header_row: number;
            /** Columns */
            columns: string[];
            /** Row Count */
            row_count: number;
            /** Preview */
            preview: {
                [key: string]: unknown;
            }[];
            /** Headers Look Misplaced */
            headers_look_misplaced: boolean;
            /** Suggested Header Row */
            suggested_header_row: number;
            /** Suggested Mapping */
            suggested_mapping: {
                [key: string]: string | null;
            };
        };
        /** ToolOut */
        ToolOut: {
            /** Line No */
            line_no: number;
            /** Listing */
            listing: string | null;
            /** Code */
            code: string | null;
            /** Description */
            description: string | null;
            /** Category */
            category: string | null;
            /** Size */
            size: string | null;
            /** Pack Units */
            pack_units: number | null;
            /** System Category */
            system_category: string | null;
            /** Cabinet Type */
            cabinet_type: string | null;
            /** Supply Point */
            supply_point: number | null;
            /** Monthly Pcs */
            monthly_pcs: number | null;
            /** Monthly Packs */
            monthly_packs: number | null;
            /** Spirals */
            spirals: number | null;
            /** Compartments */
            compartments: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkbookOut */
        WorkbookOut: {
            /** Id */
            id: number;
            /** Sha256 */
            sha256: string;
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Sheets */
            sheets: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    defaults_api_v1_settings_defaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultsOut"];
                };
            };
        };
    };
    upload_workbook_api_v1_workbooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_workbook_api_v1_workbooks_post"];
            };
        };
        responses: {
            /** @description Already stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkbookOut"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkbookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_sheet_api_v1_workbooks__workbook_id__sheets__sheet__get: {
        parameters: {
            query?: {
                header_row?: number;
            };
            header?: never;
            path: {
                workbook_id: number;
                sheet: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_mapping_api_v1_workbooks__workbook_id__mapping_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workbook_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingCheckIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingCheckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Identical finished run reused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_tools_api_v1_runs__run_id__tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_workbook_api_v1_runs__run_id__workbook_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": unknown;
                };
            };
            /** @description Run not finished */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
